### ISSUE TITLE
AADSTS90014: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by A-Kimpton** [murbanski/omniauth-microsoft-office365#11]
Hey,

So i'm trying to get logins to work, however when a user clicks login, im given this message:
`AADSTS90014: The request body must contain the following parameter: 'client_id'.`

If I use:
`provider :microsoft_office365, ENV['OFFICE365_KEY'], ENV['OFFICE365_SECRET']`
the error above is shown.
However if I use:
`provider :microsoft_office365, 'OFFICE365_KEY', 'OFFICE365_SECRET'`
The error goes away... and works as intended

I'm fairly new to rails (Java/Scala developer) so I'm not sure how I would even attempt to understand why.

Cheers.

**Comment by mjhough** [comment]
I'm having the same issue. I can get omniauth to work with Google, but not Office365 for some reason.

**Comment by 1Mark** [comment]
Make sure your `OFFICE_365KEY`  is the application ID and not the object id?
