### ISSUE TITLE
Allow restriction of access by domain

### ISSUE THREAD

**Issue by jiama843** [murbanski/omniauth-microsoft-office365#14]
Add the option similar to google OAuth2 that allows restriction of emails to a particular domain. 

i.e people with outlook.com emails can't sign in when only example.com emails are allowed.

**Comment by meatherly** [comment]
This might be helpful. Though you have to have a premium plan to use user groups :disappointed: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

**Comment by murbanski** [comment]
Merged
