### ISSUE TITLE
Don't fail if user avatar is inaccessible

### ISSUE THREAD

**Issue by mischmaesch** [murbanski/omniauth-microsoft-office365#18]
Hi.

We had a case where the authentication failed because of insufficient permissions for the user photo.

The error message is:
```
ERROR -- omniauth: (microsoft_office365) Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>"UnknownError", "message"=>"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /api/v2.0/Users('[XYZ]')/Photo/$value\non this server.<br />\n</p>\n</body></html>\n", "innerError"=>{"date"=>"2021-02-23T12:03:04", "request-id"=>"ed1f7723-2a40-43ee-b746-463fbb83c1fa", "client-request-id"=>"ed1f7723-2a40-43ee-b746-463fbb83c1fa"}}:
```
The root cause for this definitly is on Microsofts side, but I think the authorization should not fail if the avatar is inaccessible.

Can this error be handled the same way as if the user has no avatar?

We would be happy to provide a PR if time allows.

**Comment by murbanski** [comment]
I think a pull request that I have just merged might solve your problem:
https://github.com/murbanski/omniauth-microsoft-office365/pull/17

**Comment by mischmaesch** [comment]
Awesome, thanks!
