### ISSUE TITLE
Get photo not working

### ISSUE THREAD

**Issue by brandonhilkert** [murbanski/omniauth-microsoft-office365#3]
Does getting the avatar work for you?

I get the following response:

``` json
{
    "error": {
        "code": "GetUserPhoto",
        "message": "The operation is not supported."
    }
}
```

If it does work, what scopes are you requesting?

**Comment by murbanski** [comment]
Yup, it does. I get something like this:

``` ruby
[3] pry(User)> auth.info
=> {"email"=>"xxx@yyy.com",
 "display_name"=>"xxx",
 "first_name"=>"xxx",
 "last_name"=>"xxx",
 "image"=>#<File:/var/folders/34/3n1g8r61103ddvbryfchrdsm0000gn/T/avatar20160413-61146-a1x4hn.jpeg>,
 "alias"=>"xxx"}
```

And I use the default scope of this gem:
`"openid email profile https://outlook.office.com/contacts.read"`

**Comment by brandonhilkert** [comment]
Weird. Doesn't work at all for me :/

**Comment by murbanski** [comment]
Here's the exact API endpoint we hit: https://msdn.microsoft.com/en-us/office/office365/api/photo-rest-operations#UserphotooperationsGetphoto

**Comment by brandonhilkert** [comment]
Not sure if this has something to do with just having a public Outlook.com address vs. Office365, but even in the sandbox, it says it's not supported. I'll just fork it for now.

**Comment by murbanski** [comment]
Just tested this on the updated version of the gem (`0.0.5`) but nothing's changed - avatars work as usual in my case. Is it possible that for some reason avatars are not supported for your type of account? Microsoft is weird at times...

**Comment by brandonhilkert** [comment]
No idea. I'm pretty unfamiliar with their eco-system. Just trying to get read access to the mailbox. Also took me a bit to realize I need to request the `offline_access` scope. 

Another thing is that `DisplayName` is coming back as "[first name] [last name]" and it looks like the parsing of it is expecting "[last name], [first name]". Not really sure what to make of all these differences.

**Comment by jharbert** [comment]
I'm seeing this too.  When I log in from an Office365 account it looks fine, but when I instead try my Live/Outlook account it fails:

```
Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>"GetUserPhoto", "message"=>"The operation is not supported."}:
```

**Comment by murbanski** [comment]
Ha! That's why I never saw this problem: we're always using Office365 account here and I implemented the simplest possible solution to cover our case. Thanks a lot @brandonhilkert and @jharbert! I just released version `0.0.6` of the gem with all things fixed.

**Comment by dfloresgonz** [comment]
So just office365 accounts right? can the user photo from a regular hotmail or outlook account be retrieved?

**Comment by worthy7** [comment]
Bump, getting this on a very basic MS account (which is using my gmail email address).

There is this little note on this (slightly similar) API endpoint:
https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0

> Note This operation in version 1.0 supports only a user's work or school mailboxes and not personal mailboxes.
