### ISSUE TITLE
Authentication failure! invalid_credentials: OAuth2::Error, temporarily_unavailable

### ISSUE THREAD

**Issue by reubenbrown** [murbanski/omniauth-microsoft-office365#8]
I'm trying to setup authorization for a user to access their outlook account and am running into a strange error. Below is my relevant setup:

First I went to the app portal (https://apps.dev.microsoft.com/) to create my app and generate my client_id and secret as well as set my redirect_uri 

Then in my devise initializer I configured omniauth to use microsoft_office365

```
config.omniauth :microsoft_office365, ENV['MICROSOFT_CLIENT_ID'], ENV['MICROSOFT_CLIENT_SECRET'], scope: 'offline_access https://outlook.office.com/calendars.read', redirect_uri: ENV['MICROSOFT_CALLBACK_URI'], provider_ignores_state: true
```

After selecting an account to authorize in the authorize path I get this error:

```
Authentication failure! invalid_credentials: OAuth2::Error, temporarily_unavailable: AADSTS70012
```

The error message makes it unclear what exactly is wrong with my credentials. I can't find any documentation online regarding what the `AADSTS70012` error code means. 

I realize this may not be a bug with this gem but I'm not sure where else to get help figuring out what's going on here. 

Some other background: 

* Without the `provider_ignores_state` option I get a csrf error. There is a lengthy conversation about that error [here](https://github.com/intridea/omniauth-oauth2/issues/58). I can confirm that my `session['omniauth.state']` value is overwritten on the callback causing the csrf error. The solutions proposed in that thread haven't worked for me. I'm guessing the error I'm seeing and this csrf issue are related but it isn't clear how. 
* I am using an outlook account to test authorization. I noticed in @jharbert's comment [here](https://github.com/murbanski/omniauth-microsoft-office365/issues/3#issuecomment-212641284) that the api may behave differently depending on if you're using an outlook email or an office365 email to authorize. May this be the issue?

**Comment by jharbert** [comment]
@reubenbrown - Hm.. wish I could be more of a help but I'm not sure about that one.  I'd try some other types of MSFT accounts to see what happens

**Comment by reubenbrown** [comment]
@jharbert So when I tried with an office365 account and got this: 
```
"error":"invalid_client","error_description":"AADSTS70002: 
The request body must contain the following parameter: 'client_secret or client_assertion
```
This helpful message made me realize I had misspelled my client secret and therefore wasn't being included in the request. Can't believe I missed that earlier! With that fixed authorization is working normally.
